### ISSUE TITLE
pip install awslambdaric breaks because of an issue with curl in python3.12.3 alpine image

### ISSUE THREAD

**Issue by kiran-parakkalkalam-cresset** [aws/aws-lambda-python-runtime-interface-client#145] opened 2024-05-29 10:06 UTC
I have a python-alpine image version 3.12.3.

`pip install --no-cache-dir awslambdaric==2.0.8` started breaking after a curl update on May 22nd 2024. Here is the error that I am getting:

```
checking curl version... 7.83.1
./configure: line 6673: syntax error: unexpected ";;" (expecting "fi")
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-h7w2jz0q/awslambdaric_bbc032d8006c44a884d65507609b67ae/setup.py", line 98, in <module>
       ext_modules=get_runtime_client_extension(),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-install-h7w2jz0q/awslambdaric_bbc032d8006c44a884d65507609b67ae/setup.py", line 46, in       get_runtime_client_extension
extra_link_args=get_curl_extra_linker_flags(),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-install-h7w2jz0q/awslambdaric_bbc032d8006c44a884d65507609b67ae/setup.py", line 19, in get_curl_extra_linker_flags
check_call(["./scripts/preinstall.sh"])
File "/usr/local/lib/python3.12/subprocess.py", line 413, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./scripts/preinstall.sh']' returned non-zero exit status 2.
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

Curl has released a new version on May 22nd 2024, after that, this has started to fail. 

Please help us resolve this issue.

**Comment by myersjustinc** [comment] 2024-06-03 19:19
I'm running into the same, although I think it also could be related to #144 (autoconf release, rather than curl).

**Comment by m-rph** [comment] 2024-06-11 12:07
Hi, could you provide some more details about the docker image that you are using?
I am interested in the c++ dependencies.

**Comment by m-rph** [comment] 2024-06-11 18:31
Closing as duplicate of #144

**Closed by m-rph** 2024-06-11 18:31 UTC
